version: '3.4'

services:

  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "sqlserverlongpassword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - localdev

  commandergql.api:
    image: ${DOCKER_REGISTRY-}commandergqlapi
    build:
      context: .
      dockerfile: CommanderGql.Api/Dockerfile
    depends_on:
     - sql-server
    networks:
      - localdev

networks : 
  localdev:
    name: localdev
